//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleInsuranceProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Renew
    {
        public int Id { get; set; }
        public Nullable<int> Veh_Id { get; set; }
        public string Policy_Type { get; set; }
        public System.DateTime Policy_Renew_Date { get; set; }
        public System.DateTime Policy_Expiry_Date { get; set; }
        public Nullable<int> Pol_Id { get; set; }
        public int Policy_Renew_Duration { get; set; }
    
        public virtual tbl_Policy tbl_Policy { get; set; }
        public virtual tbl_VehicleInfo tbl_VehicleInfo { get; set; }
    }
}
