//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleInsuranceProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class tbl_RenewPolicy
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Policy_Type { get; set; }
        [DataMember]
        public Nullable<int> Duration { get; set; }
        [DataMember]
        public Nullable<int> Veh_Id { get; set; }
        [DataMember]
        public int Policy_Amount { get; set; }
        [DataMember]
        public Nullable<System.DateTime> Policy_StartDate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> Policy_Purchase_Date { get; set; }
        [DataMember]
        public Nullable<int> Total_IDV { get; set; }
        [DataMember]
        public Nullable<System.DateTime> Policy_Expiry_Date { get; set; }
        [DataMember]
        public string Approved_By { get; set; }
        [DataMember]
        public string Policy_Approve_Status { get; set; }
        [DataMember]
        public string Policy_Payment_Status { get; set; }
        [DataMember]
        public Nullable<int> previousPolicyId { get; set; }
        [DataMember]
    
        public virtual tbl_Policies tbl_Policies { get; set; }
        [DataMember]
        public virtual tbl_VehicleInfo tbl_VehicleInfo { get; set; }
    }
}
