//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleInsuranceProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class tbl_VehicleInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_VehicleInfo()
        {
            this.tbl_Policy = new HashSet<tbl_Policy>();
            this.tbl_Renew = new HashSet<tbl_Renew>();
        }
    
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Vehicle_Type { get; set; }
        [DataMember]
        public string Manufacturer { get; set; }
        [DataMember]
        public string Veh_Model { get; set; }
        [DataMember]
        public string Driving_Licence { get; set; }
        [DataMember]
        public System.DateTime Purchase_Date { get; set; }
        [DataMember]
        public string Registration_Number { get; set; }
        [DataMember]
        public string Engine_No { get; set; }
        [DataMember]
        public string ChasisNo { get; set; }
        [DataMember]
        public Nullable<int> Cust_Id { get; set; }
        
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<tbl_Policy> tbl_Policy { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        
        public virtual ICollection<tbl_Renew> tbl_Renew { get; set; }
        [DataMember]
        public virtual tbl_User tbl_User { get; set; }
        [DataMember]
        public virtual tbl_Vehicle_Price tbl_Vehicle_Price { get; set; }
    }
}
