//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleInsuranceProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Policy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Policy()
        {
            this.tbl_Claim = new HashSet<tbl_Claim>();
            this.tbl_Payment = new HashSet<tbl_Payment>();
            this.tbl_Renew = new HashSet<tbl_Renew>();
        }
    
        public int Id { get; set; }
        public string Policy_Type { get; set; }
        public int Duration { get; set; }
        public Nullable<int> Veh_Id { get; set; }
        public int Policy_Amount { get; set; }
        public System.DateTime Policy_Date { get; set; }
        public System.DateTime Policy_Purchase_Date { get; set; }
        public int Total_IDV { get; set; }
        public Nullable<System.DateTime> Policy_Expiry_Date { get; set; }
        public string Approved_By { get; set; }
        public string Policy_Approve_Status { get; set; }
        public string Policy_Payment_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Claim> tbl_Claim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Payment> tbl_Payment { get; set; }
        public virtual tbl_VehicleInfo tbl_VehicleInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Renew> tbl_Renew { get; set; }
    }
}
