//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleInsuranceProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class tbl_Claims
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Mobile_No { get; set; }
        [DataMember]
        public string Reason_of_Claim { get; set; }
        [DataMember]
        public System.DateTime Date_Of_Claim { get; set; }
        [DataMember]
        public string Claim_Approved { get; set; }
        [DataMember]
        public int Claim_Amount { get; set; }
        [DataMember]
        public Nullable<int> Pol_Id { get; set; }
        [DataMember]
        public Nullable<int> Customer_Id { get; set; }
        [DataMember]
    
        public virtual tbl_User tbl_User { get; set; }
        [DataMember]
        public virtual tbl_Policies tbl_Policies { get; set; }
    }
}
